// <auto-generated />
using System;
using System.Text.Json;
using MediaManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaManager.Core.Entities.Album", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("Date").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<string>("Lieu").HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.AlbumMedia", b =>
                {
                    b.Property<Guid>("AlbumId").HasColumnType("uuid");
                    b.Property<Guid>("MediaId").HasColumnType("uuid");
                    b.Property<int>("Order").HasColumnType("integer");
                    b.HasKey("AlbumId", "MediaId");
                    b.HasIndex("MediaId");
                    b.ToTable("AlbumMedia");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("MediaId").HasColumnType("uuid");
                    b.Property<Guid>("AuthorId").HasColumnType("uuid");
                    b.Property<string>("AuthorName").IsRequired().HasColumnType("text");
                    b.Property<string>("AuthorAvatar").HasColumnType("text");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("MediaId");
                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Media", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<float?>("DurationSeconds").HasColumnType("real");
                    b.Property<string>("Filename").IsRequired().HasColumnType("text");
                    b.Property<int?>("Height").HasColumnType("integer");
                    b.Property<string>("Lieu").HasColumnType("text");
                    b.Property<Point>("Location").HasColumnType("geometry(Point, 4326)");
                    b.Property<JsonDocument>("Metadata").HasColumnType("jsonb");
                    b.Property<string>("MimeType").HasColumnType("text");
                    b.Property<long>("SizeBytes").HasColumnType("bigint");
                    b.Property<string>("StorageKey").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("TakenAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("Type").HasColumnType("integer");
                    b.Property<int?>("Width").HasColumnType("integer");
                    b.Property<Guid?>("UploadedById").HasColumnType("uuid");
                    b.Property<string>("UploadedByName").HasColumnType("text");
                    b.Property<string>("UploadedByAvatar").HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Media");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.MediaTag", b =>
                {
                    b.Property<Guid>("MediaId").HasColumnType("uuid");
                    b.Property<Guid>("TagId").HasColumnType("uuid");
                    b.HasKey("MediaId", "TagId");
                    b.HasIndex("TagId");
                    b.ToTable("MediaTags");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("MediaId").HasColumnType("uuid");
                    b.Property<Guid>("AuthorId").HasColumnType("uuid");
                    b.Property<string>("AuthorName").IsRequired().HasColumnType("text");
                    b.Property<string>("Emoji").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex(new[] { "MediaId", "AuthorId", "Emoji" }, name: "IX_Reactions_MediaId_AuthorId_Emoji").IsUnique();
                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.AlbumMedia", b =>
                {
                    b.HasOne("MediaManager.Core.Entities.Album", "Album")
                        .WithMany("AlbumMedia").HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MediaManager.Core.Entities.Media", "Media")
                        .WithMany("AlbumMedia").HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Album");
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Comment", b =>
                {
                    b.HasOne("MediaManager.Core.Entities.Media", "Media")
                        .WithMany("Comments").HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.MediaTag", b =>
                {
                    b.HasOne("MediaManager.Core.Entities.Media", "Media")
                        .WithMany("MediaTags").HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MediaManager.Core.Entities.Tag", "Tag")
                        .WithMany("MediaTags").HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Media");
                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Reaction", b =>
                {
                    b.HasOne("MediaManager.Core.Entities.Media", "Media")
                        .WithMany("Reactions").HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Album", b =>
                {
                    b.Navigation("AlbumMedia");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Media", b =>
                {
                    b.Navigation("AlbumMedia");
                    b.Navigation("MediaTags");
                    b.Navigation("Comments");
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("MediaManager.Core.Entities.Tag", b =>
                {
                    b.Navigation("MediaTags");
                });
#pragma warning restore 612, 618
        }
    }
}
