server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compression gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    gzip_min_length 1024;

    # Proxy UserManager API — même origine = cookie SameSite:Lax envoyé
    location /user-api/ {
        proxy_pass http://user-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy GED API
    location /ged-api/ {
        proxy_pass http://ged-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Cache assets immutables (hash dans le nom)
    location ~* \.(?:js|css|woff2?|png|jpg|svg|ico)$ {
        expires 1h;
        add_header Cache-Control "public, must-revalidate";
        try_files $uri =404;
    }

    # SPA fallback — toutes les routes renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
